version: "3"
services:
  node:
    image: node:8
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api/:/home/node/app
    ports:
      - "8081:3000"
    command: npm start

  app:
    image: node:8
    working_dir: /home/react/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app/:/home/react/app
    ports:
      - "8080:3000"
    command: npm start
