version: "3"
services:
  # mysql:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #   ports:
  #     - 3306:3306
  # elk:
  #   image: sebp/elk
  #   container_name: elk
  #   ports:
  #     - "5601:5601" #kibana
  #     - "9200:9200" #ES
  #     - "5044:5044" #logstash
  api:
    image: node:8
    container_name: api
    working_dir: /home/api
    environment:
      - NODE_ENV=production
    volumes:
      - ./api/:/home/api
    ports:
      - "8081:3000"
    command: npm start
  app:
    image: node:8
    container_name: app
    working_dir: /home/app
    environment:
      - REACT_APP_API_URL=localhost
      - REACT_APP_API_PORT=8081
    volumes:
      - ./app/:/home/app
    ports:
      - "8080:3000"
    command: npm start
