version: "3"
services:
  api:
    image: node:8
    container_name: api
    working_dir: /home/api
    environment:
      - NODE_ENV=production
    volumes:
      - ./api/:/home/api
    ports:
      - "8081:3000"
    command: npm start

  app:
    image: node:8
    container_name: app
    working_dir: /home/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app/:/home/app
    ports:
      - "8080:3000"
    command: npm start
