FROM debian

RUN apt-get update
RUN apt-get install -y python3 python3-pip

WORKDIR /apptest

COPY . /apptest

RUN python3 -m pip install --trusted-host pypi.python.org -r requirements.txt


EXPOSE 80

ENV NAME World

CMD ["python3", "./app.py"]