---
- name: Install webapp and api
  hosts: web
  remote_user: root
  become: yes
  tasks:
    - docker_service:
        project_name: nodejs
        definition:
          version: '1'
          services:
            api:
              image: node:8
              container_name: api
              working_dir: /home/api
              environment:
                - NODE_ENV=production
              volumes:
                - ./api/:/home/api
              ports:
                - "8001:3000"
              command: npm start
            app:
              image: node:8
              container_name: app
              working_dir: /hom/app
              environment:
                - REACT_APP_API_URL=localhost
                - REACT_APP_API_PORT=8001
              volumes:
                - ./app/:/home/app
              ports:
                - "8000:3000"
              command: npm start
